#!/usr/bin/env bash
CONF_DIR=$PREFIX/etc/test
DEST=$CONF_DIR/installed/alpine
echo -e "Starting Installer"
apt install proot curl tar --assume-yes
if [ -d ${DEST} ]; then
  echo "Alpine Is Already Installed, Do You Want To Re-Install?"
  read ask
  if [ "${ask}" = "y" ]; then
    rm -rf ${DEST}
  elif [ "${ask}" = "n" ]; then
		exit 1
  else
      printf "Wrong Input/n"
      exit 1
    fi
fi
mkdir ${DEST}

unknownarch() {
  echo "[*] Unknown Arch"
  exit 1
}

checksysinfo() {
	printf "[*] Checking host architecture ...\n"
	case $(getprop ro.product.cpu.abi) in
		arm64-v8a)
			SETARCH=aarch64
			;;
		armeabi|armeabi-v7a)
			SETARCH=armhf
			;;
		x86|i686)
			SETARCH=x86
			;;
		x86_64)
			SETARCH=x86_64
			;;
		*)
			unknownarch
			;;
	esac
}

extract() {
  echo "Starting Extraction"
  proot --link2symlink -0 tar -xf $CONF_DIR/caches/$ROOTFS -C $DEST >/dev/null
  printf " [OK]"
}

internet() {
  echo "Setting Up Internet"
  echo 'nameserver 1.1.1.1' > $DEST/etc/resolv.conf
  printf "[OK] "
}

seturl() {
  echo "Getting File"
  cd ${DEST}; curl -s http://dl-cdn.alpinelinux.org/alpine/edge/releases/${SETARCH}/alpine-minirootfs-3.10.0-${SETARCH}.tar.gz
  printf " [OK]"
  rootfs=${DEST}/alpine-minirootfs-3.10.0-${SETARCH}.tar.gz
}

checksysinfo
getalpine
extract
printf "[OK] Download Completed\n"
exit 0
printf "\n"



